CREATE TABLE IF NOT EXISTS hardware (
     id   INTEGER NOT NULL AUTO_INCREMENT,
     code VARCHAR(255) NOT NULL,
     name VARCHAR(128) NOT NULL,
     price DOUBLE NOT NULL ,
     type VARCHAR(128) NOT NULL ,
     quantity INTEGER NOT NULL,
     PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS review (
    id   INTEGER NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    text VARCHAR(255) NOT NULL,
    score INTEGER NOT NULL ,
    hardware_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (hardware_id) REFERENCES hardware(id)
);